# Generated by Django 4.0.4 on 2022-11-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees_alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('course', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('registrationDate', models.DateField(verbose_name='Registration Date')),
                ('completionDate', models.DateField(verbose_name='Completion Date')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users')),
            ],
        ),
    ]
