# Generated by Django 4.0.4 on 2023-01-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_trainees_general_training_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainees_general',
            name='level',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
