# Generated by Django 4.0.4 on 2023-01-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interns',
            name='attached_area',
        ),
        migrations.AddField(
            model_name='interns',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='interns',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=80000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='interns',
            name='course_duration',
            field=models.CharField(default='3 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='interns',
            name='course_learning',
            field=models.CharField(default='Frontend Web Development', max_length=50),
        ),
        migrations.AddField(
            model_name='interns',
            name='training_fee',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
    ]
