# Generated by Django 4.0.4 on 2023-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_remove_interns_attached_area_interns_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='level',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
